/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerDeliveriesRouteImport } from './routes/partner.deliveries'
import { Route as PartnerDocumentsRouteImport } from './routes/partner.documents'
import { Route as PartnerEarningsRouteImport } from './routes/partner.earnings'
import { Route as PartnerReferralRouteImport } from './routes/partner.referral'
import { Route as PartnerRentalsRouteImport } from './routes/partner.rentals'
import { Route as VendorModuleRouteImport } from './routes/vendor.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDeliveriesRoute = PartnerDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDocumentsRoute = PartnerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerEarningsRoute = PartnerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerReferralRoute = PartnerReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerRentalsRoute = PartnerRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => PartnerRoute,
} as any)
const VendorModuleRoute = VendorModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => VendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/partner': typeof PartnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRouteWithChildren
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/partner/rentals': typeof PartnerRentalsRoute
  '/vendor/$module': typeof VendorModuleRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRouteWithChildren
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/partner/rentals': typeof PartnerRentalsRoute
  '/vendor/$module': typeof VendorModuleRoute
  '/partner': typeof PartnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/partner': typeof PartnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/vendor': typeof VendorRouteWithChildren
  '/partner/deliveries': typeof PartnerDeliveriesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/earnings': typeof PartnerEarningsRoute
  '/partner/referral': typeof PartnerReferralRoute
  '/partner/rentals': typeof PartnerRentalsRoute
  '/vendor/$module': typeof VendorModuleRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/partner'
    | '/register'
    | '/vendor'
    | '/partner/deliveries'
    | '/partner/documents'
    | '/partner/earnings'
    | '/partner/referral'
    | '/partner/rentals'
    | '/vendor/$module'
    | '/partner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/register'
    | '/vendor'
    | '/partner/deliveries'
    | '/partner/documents'
    | '/partner/earnings'
    | '/partner/referral'
    | '/partner/rentals'
    | '/vendor/$module'
    | '/partner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/partner'
    | '/register'
    | '/vendor'
    | '/partner/deliveries'
    | '/partner/documents'
    | '/partner/earnings'
    | '/partner/referral'
    | '/partner/rentals'
    | '/vendor/$module'
    | '/partner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VendorRoute: typeof VendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/deliveries': {
      id: '/partner/deliveries'
      path: '/deliveries'
      fullPath: '/partner/deliveries'
      preLoaderRoute: typeof PartnerDeliveriesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/documents': {
      id: '/partner/documents'
      path: '/documents'
      fullPath: '/partner/documents'
      preLoaderRoute: typeof PartnerDocumentsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/earnings': {
      id: '/partner/earnings'
      path: '/earnings'
      fullPath: '/partner/earnings'
      preLoaderRoute: typeof PartnerEarningsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/referral': {
      id: '/partner/referral'
      path: '/referral'
      fullPath: '/partner/referral'
      preLoaderRoute: typeof PartnerReferralRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/rentals': {
      id: '/partner/rentals'
      path: '/rentals'
      fullPath: '/partner/rentals'
      preLoaderRoute: typeof PartnerRentalsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/vendor/$module': {
      id: '/vendor/$module'
      path: '/$module'
      fullPath: '/vendor/$module'
      preLoaderRoute: typeof VendorModuleRouteImport
      parentRoute: typeof VendorRoute
    }
  }
}

interface PartnerRouteChildren {
  PartnerDeliveriesRoute: typeof PartnerDeliveriesRoute
  PartnerDocumentsRoute: typeof PartnerDocumentsRoute
  PartnerEarningsRoute: typeof PartnerEarningsRoute
  PartnerReferralRoute: typeof PartnerReferralRoute
  PartnerRentalsRoute: typeof PartnerRentalsRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerDeliveriesRoute: PartnerDeliveriesRoute,
  PartnerDocumentsRoute: PartnerDocumentsRoute,
  PartnerEarningsRoute: PartnerEarningsRoute,
  PartnerReferralRoute: PartnerReferralRoute,
  PartnerRentalsRoute: PartnerRentalsRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface VendorRouteChildren {
  VendorModuleRoute: typeof VendorModuleRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorModuleRoute: VendorModuleRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PartnerRoute: PartnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VendorRoute: VendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
